@extends('web.layouts.layout')
@section('title', 'Trang chủ')
@section('content')
    @include('web.banners.slider', ['data' => $banner])
    @include('web.services.services')
    @include('web.shop.shop-product-row', ['newProduct' => $newestProduct])
    @include('web.shop.shop-product-best-seller', ['promoteProduct' => $promoteProduct])
    @include('web.banners.banner-2')
    @include('web.about.about',['categoriesProduct' => $hotProductCategory])
    @include('web.news.new-home',['hotNews' => $hotNews])
    @include('web.partners.partner')
@endsection
