<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ProductCategory\CreateProductCategoryRequest;
use App\Http\Requests\Admin\ProductCategory\UpdateProductCategoryRequest;
use App\Models\ProductCategory;
use Illuminate\Http\Request;

class ProductCategoryController extends ResourceController
{
    protected $model = ProductCategory::class;
    protected $viewPath = 'product_category';
    protected $name = 'Danh mục sản phẩm';
    protected $route = 'product_category';

    /**
     * Create page
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $listParent = ProductCategory::pluck('name', 'id')->toArray();
        $this->data = [
            'listParent' => $listParent
        ];
        return parent::create();
    }

    /**
     * Store a category
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request,
            (new CreateProductCategoryRequest())->rules(),
            [],
            (new CreateProductCategoryRequest())->attributes());

        return parent::store($request); // TODO: Change the autogenerated stub
    }


    /**
     * Edit page, edit a category
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $listParent = ProductCategory::pluck('name', 'id')->toArray();
        $this->data = [
            'pageTitle' => 'Sửa danh mục sản phẩm',
            'listParent' => $listParent
        ];
        return parent::edit($id);
    }

    /**
     * update a category
     *
     * @param Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,
            (new UpdateProductCategoryRequest())->rules(),
            [],
            (new UpdateProductCategoryRequest())->attributes());

        $this->updateData = [
            'name' => $request->name,
            'parent_id' => $request->parent_id,
            'link' => $request->link,
            'image' => $request->image,
            'description' => $request->description,
            'is_hot' => $request->is_hot
        ];

        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }
}
?>
